version: "2"

services:

  team-service:
    build: ./table-tennis-team-service
    ports:
      - 9001:9000
      - 5006:5005
    volumes:
      - "./table-tennis-team-service:/opt/table-tennis-team-service"
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"
    environment:
      # DATABASE_URL: "jdbc:mysql://root:password@mysql-database:3306/table_tennis"
      DATABASE_URL: "jdbc:postgresql://postgres-database:5432/table_tennis?user=postgres_user&password=password"

  results-service:
    build: ./table-tennis-results-service
    ports:
      - 9000:9000
      - 5005:5005
    volumes:
      - "./table-tennis-results-service:/opt/table-tennis-results-service"
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"
    environment:
      TEAM_SERVICE_URL: "http://team-service:9000"

  web-app:
    build: ./table-tennis-web
    ports:
      - 8000:8000
    volumes:
      - "./table-tennis-web/app:/opt/table-tennis-web/app"

  postgres-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres_user"
      POSTGRES_DB: "table_tennis"

  mysql-database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "table_tennis"